name: flutter_shuke
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  cached_network_image: ^1.1.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.2
  url_launcher: ^5.0.2
  flutter_webview_plugin: ^0.3.1
  sqflite: ^1.1.3
  dio: ^2.1.0
  flutter_swiper: ^1.0.6
  flutter_screenutil: ^0.5.1
  video_player: ^0.10.2+1
  rxdart: ^0.22.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets: 需要和 uses-material-design: true 左对齐，否则编译会报错。。。
  assets:
    #tabbar - item - icon
    - assets/images/explore_icon_def.png
    - assets/images/2.0x/explore_icon_def.png
    - assets/images/3.0x/explore_icon_def.png
    - assets/images/explore_icon_sel.png
    - assets/images/2.0x/explore_icon_sel.png
    - assets/images/3.0x/explore_icon_sel.png

    - assets/images/home_icon_def.png
    - assets/images/2.0x/home_icon_def.png
    - assets/images/3.0x/home_icon_def.png
    - assets/images/home_icon_sel.png
    - assets/images/2.0x/home_icon_sel.png
    - assets/images/3.0x/home_icon_sel.png

    - assets/images/im_icon_def.png
    - assets/images/2.0x/im_icon_def.png
    - assets/images/3.0x/im_icon_def.png
    - assets/images/im_icon_sel.png
    - assets/images/2.0x/im_icon_sel.png
    - assets/images/3.0x/im_icon_sel.png

    - assets/images/mine_icon_def.png
    - assets/images/2.0x/mine_icon_def.png
    - assets/images/3.0x/mine_icon_def.png
    - assets/images/mine_icon_sel.png
    - assets/images/2.0x/mine_icon_sel.png
    - assets/images/3.0x/mine_icon_sel.png

    - assets/images/server_icon_def.png
    - assets/images/2.0x/server_icon_def.png
    - assets/images/3.0x/server_icon_def.png
    - assets/images/server_icon_sel.png
    - assets/images/2.0x/server_icon_sel.png
    - assets/images/3.0x/server_icon_sel.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  #ttf的矢量图标:
  fonts:
    #先定义.ttf矢量图标文件在flutter中的名称
    - family: AppTabbarIconFonts
      #tf文件在flutter工程中的绝对路径:
      fonts:
        - asset: assets/images/fonts/tabbarIconfont.ttf